version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  deploy:
    executor:
      name: node/default
      tag: 13
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run deploy
          name: Run deployment to screeps

workflows:
  deployment:
    jobs:
      - deploy
