version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  install:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn printvars
          name: Printing environment variables
      - run:
          command: yarn deploy
          name: Run deployment to screeps

workflows:
  deployment:
    jobs:
      - install
      - deploy
