version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  install:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn eslint
          name: ESLint
      - run:
          command: yarn compile
          name: Compile files
      - run:
          command: |
            echo "export SCREEPS_BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
          name: Setup branch
      - run:
          command: yarn deploy
          name: Run deployment to screeps

workflows:
  deployment:
    jobs:
      - install
      - deploy
