export const WORLD_STATE_BUCKET = {
  POPULATION: 'professionPopulation',
  SOURCE_MINING: 'sourceMining',
  MULE_ORDERS: 'muleOrders',
  ENERGY_ORDERS: 'energyOrders',
  ROADS: 'roads',
  BUILDINGS: 'buildings',
};

export const ALL_STATES = [
  WORLD_STATE_BUCKET.POPULATION,
  WORLD_STATE_BUCKET.SOURCE_MINING,
  WORLD_STATE_BUCKET.MULE_ORDERS,
  WORLD_STATE_BUCKET.ENERGY_ORDERS,
  WORLD_STATE_BUCKET.ROADS,
  WORLD_STATE_BUCKET.BUILDINGS,
];
